name: CI with Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create a file
      run: echo "Build completed on $(date)" > result.txt

    - name: Upload result file
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: result.txt
